CREATE TABLE "GACTT_RESULTS_ANONYMIZED_v2" (
	"Submission ID" VARCHAR NOT NULL, 
	"What is your age?" VARCHAR, 
	"How many cups of coffee do you typically drink per day?" VARCHAR, 
	"Where do you typically drink coffee?" VARCHAR, 
	"Where do you typically drink coffee? (At home)" BOOLEAN, 
	"Where do you typically drink coffee? (At the office)" BOOLEAN, 
	"Where do you typically drink coffee? (On the go)" BOOLEAN, 
	"Where do you typically drink coffee? (At a cafe)" BOOLEAN, 
	"Where do you typically drink coffee? (None of these)" BOOLEAN, 
	"How do you brew coffee at home?" VARCHAR, 
	"How do you brew coffee at home? (Pour over)" BOOLEAN, 
	"How do you brew coffee at home? (French press)" BOOLEAN, 
	"How do you brew coffee at home? (Espresso)" BOOLEAN, 
	"How do you brew coffee at home? (Coffee brewing machine (e.g. Mr. Coffee))" BOOLEAN, 
	"How do you brew coffee at home? (Pod/capsule machine (e.g. Keurig/Nespresso))" BOOLEAN, 
	"How do you brew coffee at home? (Instant coffee)" BOOLEAN, 
	"How do you brew coffee at home? (Bean-to-cup machine)" BOOLEAN, 
	"How do you brew coffee at home? (Cold brew)" BOOLEAN, 
	"How do you brew coffee at home? (Coffee extract (e.g. Cometeer))" BOOLEAN, 
	"How do you brew coffee at home? (Other)" BOOLEAN, 
	"How else do you brew coffee at home?" VARCHAR, 
	"On the go, where do you typically purchase coffee?" VARCHAR, 
	"On the go, where do you typically purchase coffee? (National chain (e.g. Starbucks, Dunkin))" BOOLEAN, 
	"On the go, where do you typically purchase coffee? (Local cafe)" BOOLEAN, 
	"On the go, where do you typically purchase coffee? (Drive-thru)" BOOLEAN, 
	"On the go, where do you typically purchase coffee? (Specialty coffee shop)" BOOLEAN, 
	"On the go, where do you typically purchase coffee? (Deli or supermarket)" BOOLEAN, 
	"On the go, where do you typically purchase coffee? (Other)" BOOLEAN, 
	"Where else do you purchase coffee?" VARCHAR, 
	"What is your favorite coffee drink?" VARCHAR, 
	"Please specify what your favorite coffee drink is" VARCHAR, 
	"Do you usually add anything to your coffee?" VARCHAR, 
	"Do you usually add anything to your coffee? (No - just black)" BOOLEAN, 
	"Do you usually add anything to your coffee? (Milk, dairy alternative, or coffee creamer)" BOOLEAN, 
	"Do you usually add anything to your coffee? (Sugar or sweetener)" BOOLEAN, 
	"Do you usually add anything to your coffee? (Flavor syrup)" BOOLEAN, 
	"Do you usually add anything to your coffee? (Other)" BOOLEAN, 
	"What else do you add to your coffee?" VARCHAR, 
	"What kind of dairy do you add?" VARCHAR, 
	"What kind of dairy do you add? (Whole milk)" BOOLEAN, 
	"What kind of dairy do you add? (Skim milk)" BOOLEAN, 
	"What kind of dairy do you add? (Half and half)" BOOLEAN, 
	"What kind of dairy do you add? (Coffee creamer)" BOOLEAN, 
	"What kind of dairy do you add? (Flavored coffee creamer)" BOOLEAN, 
	"What kind of dairy do you add? (Oat milk)" BOOLEAN, 
	"What kind of dairy do you add? (Almond milk)" BOOLEAN, 
	"What kind of dairy do you add? (Soy milk)" BOOLEAN, 
	"What kind of dairy do you add? (Other)" BOOLEAN, 
	"What kind of sugar or sweetener do you add?" VARCHAR, 
	"What kind of sugar or sweetener do you add? (Granulated Sugar)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Artificial Sweeteners (e.g., Splenda))" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Honey)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Maple Syrup)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Stevia)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Agave Nectar)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Brown Sugar)" BOOLEAN, 
	"What kind of sugar or sweetener do you add? (Raw Sugar (Turbinado))" BOOLEAN, 
	"What kind of flavorings do you add?" BOOLEAN, 
	"What kind of flavorings do you add? (Vanilla Syrup)" BOOLEAN, 
	"What kind of flavorings do you add? (Caramel Syrup)" BOOLEAN, 
	"What kind of flavorings do you add? (Hazelnut Syrup)" BOOLEAN, 
	"What kind of flavorings do you add? (Cinnamon (Ground or Stick))" BOOLEAN, 
	"What kind of flavorings do you add? (Peppermint Syrup)" BOOLEAN, 
	"What kind of flavorings do you add? (Other)" BOOLEAN, 
	"What other flavoring do you use?" BOOLEAN, 
	"Before today's tasting, which of the following best described what kind of coffee you like?" VARCHAR, 
	"How strong do you like your coffee?" VARCHAR, 
	"What roast level of coffee do you prefer?" VARCHAR, 
	"How much caffeine do you like in your coffee?" VARCHAR, 
	"Lastly, how would you rate your own coffee expertise?" DECIMAL, 
	"Coffee A - Bitterness" DECIMAL, 
	"Coffee A - Acidity" DECIMAL, 
	"Coffee A - Personal Preference" DECIMAL, 
	"Coffee A - Notes" VARCHAR, 
	"Coffee B - Bitterness" DECIMAL, 
	"Coffee B - Acidity" DECIMAL, 
	"Coffee B - Personal Preference" DECIMAL, 
	"Coffee B - Notes" VARCHAR, 
	"Coffee C - Bitterness" DECIMAL, 
	"Coffee C - Acidity" DECIMAL, 
	"Coffee C - Personal Preference" DECIMAL, 
	"Coffee C - Notes" VARCHAR, 
	"Coffee D - Bitterness" DECIMAL, 
	"Coffee D - Acidity" DECIMAL, 
	"Coffee D - Personal Preference" DECIMAL, 
	"Coffee D - Notes" VARCHAR, 
	"Between Coffee A, Coffee B, and Coffee C which did you prefer?" VARCHAR, 
	"Between Coffee A and Coffee D, which did you prefer?" VARCHAR, 
	"Lastly, what was your favorite overall coffee?" VARCHAR, 
	"Do you work from home or in person?" VARCHAR, 
	"In total, much money do you typically spend on coffee in a month?" VARCHAR, 
	"Why do you drink coffee?" VARCHAR, 
	"Why do you drink coffee? (It tastes good)" BOOLEAN, 
	"Why do you drink coffee? (I need the caffeine)" BOOLEAN, 
	"Why do you drink coffee? (I need the ritual)" BOOLEAN, 
	"Why do you drink coffee? (It makes me go to the bathroom)" BOOLEAN, 
	"Why do you drink coffee? (Other)" BOOLEAN, 
	"Other reason for drinking coffee" VARCHAR, 
	"Do you like the taste of coffee?" BOOLEAN, 
	"Do you know where your coffee comes from?" BOOLEAN, 
	"What is the most you've ever paid for a cup of coffee?" VARCHAR, 
	"What is the most you'd ever be willing to pay for a cup of coffee?" VARCHAR, 
	"Do you feel like you’re getting good value for your money when you buy coffee at a cafe?" BOOLEAN, 
	"Approximately how much have you spent on coffee equipment in the past 5 years?" VARCHAR, 
	"Do you feel like you’re getting good value for your money with regards to your coffee equipment?" BOOLEAN, 
	"Gender" VARCHAR, 
	"Gender (please specify)" VARCHAR, 
	"Education Level" VARCHAR, 
	"Ethnicity/Race" VARCHAR, 
	"Ethnicity/Race (please specify)" VARCHAR, 
	"Employment Status" VARCHAR, 
	"Number of Children" VARCHAR, 
	"Political Affiliation" VARCHAR
);
